# Generated by Django 5.1.6 on 2025-02-23 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50, unique=True)),
                ('case_type', models.CharField(max_length=100)),
                ('court_name', models.CharField(max_length=255)),
                ('court_number', models.CharField(max_length=50)),
                ('magistrate_name', models.CharField(max_length=255)),
                ('petitioner', models.CharField(max_length=255)),
                ('respondent', models.CharField(max_length=255)),
                ('next_hearing_date', models.DateField()),
                ('status', models.CharField(choices=[('on-trial', 'On-Trial'), ('closed', 'Closed'), ('pending', 'Pending'), ('dismissed', 'Dismissed')], default='on-trial', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='bot.client')),
            ],
        ),
    ]
