# Generated by Django 4.2.20 on 2025-03-27 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_conversation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
